### ISSUE TITLE
Prohektanfrage

### ISSUE THREAD

**Issue by DamienLazareth** [mischak/fb5210#1]
Hi mischa, bist du an diesem Projekt noch dran? 
Im Forum erwecken deine bisherigen Ergebnisse Erwartungen :)
Könntest du deinen Code hochladen? 
Grüße

**Comment by mischak** [comment]
Hi Damien, weiss nicht, ob Du noch interessiert bist... der Hauptteil des Codes ist nun hochgeladen. Sorry für die lange Wartezeit, deine Anfrage ist mir untergegangen.
Viele Grüsse, Mischa
