### ISSUE TITLE
Dead repository

### ISSUE THREAD

**Issue by msedv** [mischak/fb5210#2]
Since this repository seems to be dead for four years I tried to summarize what Mischak and I found out at <https://github.com/msedv/FB5210>.

**Comment by mischak** [comment]
Ich habe nun den Hauptteil des Codes gepushed. Am interessantesten ist sicher der TelegramHandler.kt und der CrcCalculator.kt (resp. seine Parameter), der notwendig ist um ein gültiges Kommando für die Heizungssteuerung zu produzieren.

**Comment by msedv** [comment]
Super, großartig - vielen Dank!
